export const TAG_OPTIONS = [
  "Slow is smooth... smooth is fast",
  "Zone 5 enthusiast",
  "Suffering Efficiently",
  "Powered by Delusion",
  "New Pace Who Dis",
  "Pace Questionable",
  "Sub-35 loading...",
  "Sub-30 loading...",
  "Sub-25 loading...",
  "Sub-20 loading...",
  "Sub-whatever",
  "Elite (Locally)",
  "Consistently Mid",
  "Optimizing… Probably",
  "DOMS Specialist",
  "Breathing Optional",
  "Fueling: Vibes",
  "Built Different (Unfortunately)",
  "Mentally at Mile 20",
  "Succumbed to the zone 2 propaganda",
  "Carb Loading Daily",
  "Why Am I Like This",
  "No Plan Just Miles",
  "Fasted & Confused",
  "Perpetually Tired",
  "Soft Launching a PR",
  "Negative Split Era",
  "Hill Trauma Survivor",
];

export default TAG_OPTIONS;